### ISSUE TITLE
Problem of garbage science

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/Schloss_PrePrints_mBio_2017#13]
"3. A major hurdle for the acceptance of preprints i think is the fear that it will open the floodgates of poor science and so good research will be obscured. Although you have good examples of quick preprints to post publication peer review a person may rush publishing a preprint which is wrong and another scientist or even the media may run with this. Unfortunately it can be very hard to get the wrong information out of people's heads. I think this is unfortunately an issue of places where anyone can post stuff. " - MG

**Comment by aleimba** [comment]
I see a very similar problem with press releases and the "selling" of results. So, it might not necessarily be a problem of preprints but is a problem of the current scientific reward system (with or without peer-reviewed publications ). Nevertheless, let's see if preprint server will attract a form of internet trolling (I really hope not).

I recently had a talk with a professor at a conference, he was worried that researchers might publish sub-quality preprints to reserve a "being first" publication date and then further work on the project up to a journal submission.

**Comment by pschloss** [comment]
Agreed.

To the original comment by MG, I feel like I deal with this already in the manuscript where I state, "I would hope that both consumers of preprints and grant proposal reviewers would be able to differentiate between someone trying to game the system and someone that is using preprints as a mechanism to improve their science".

I also think that the idea of an evolving analysis and manuscript (e.g. [this](http://biorxiv.org/lookup/doi/10.1101/113100) is a unique way of disseminating research in a rapid and transparent manner.
