### ISSUE TITLE
Link preprint comments with NCBI

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/Schloss_PrePrints_mBio_2017#23]
"11. It would be nice if comments left on preprints would populate NCBI comment sections. I don't know if this will ever happen, but it would be nice to know that others have talked about papers before they are published." - DB

**Comment by aleimba** [comment]
I would also like to see an aggregation of comments on individual publications. I think PubPeer already does that with PubMed Commons, but not the other way around. There is, however, a browser plugin: http://blog.pubpeer.com/?p=29.
