### ISSUE TITLE
Future of journals

### ISSUE THREAD

**Issue by pschloss** [SchlossLab/Schloss_PrePrints_mBio_2017#4]
"I could see a world where all articles are put first on prepreint servers and 'journals' act as aggregators for peer review and professional editing/ layout etc of the most interesting in their particular field.  This could work becasue curated sites that help flag outstanding articles save academics time and add prestige. These journal sites would have to be paid for by institutional subscriptions or advertisements." - TR

**Comment by aleimba** [comment]
This rather radical approach would save a lot of money and could be run by a university infrastructure many Open Science advocates have been proposing (e.g. Björn Brembs @brembs: http://bjoern.brembs.net/2015/04/what-should-a-modern-scientific-infrastructure-look-like/). Each publication could be easily tagged by scientific field etc and a rating system could be included as in Science Open.

Putting a very "thin" peer-review level over preprint servers has already been done by Overlay Journals (https://en.wikipedia.org/wiki/Overlay_journal), e.g. in mathematics with arXiv: http://www.nature.com/news/leading-mathematician-launches-arxiv-overlay-journal-1.18351

**Comment by pschloss** [comment]
I kind of touch on this in addressing Issue #24
